- name: package installation
  hosts: local
  connection: local
  become: true

  tasks:
    - name: Manage packages
      ansible.builtin.package:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
      loop:
        - { name: "nginx", state: "present" }
        - { name: "mysql", state: "present" }
        - { name: "zip", state: "absent" }

    - name: Restart services
      ansible.builtin.service:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
      loop:
        - { name: "nginx", state: "restarted" }
        - { name: "mysql", state: "restarted" }

    - name: Display facts
      ansible.builtin.debug:
        msg: "{{ ansible_facts }}"