- name: filter
  hosts: local
  connection: local
  vars:
    topics: sunil, naveen, ravi
  tasks: 
    - name: greeting
      ansible.builtin.debug:
        msg: "Hi {{ Greeting | default ('chanakya') }}"

    - name: split
      ansible.builtin.debug:
        msg: "{{ topics | split(',') }}"
        # listjojocomma: "{{ 'jojo is, a' | split(',') }}"