- name: play variables
  hosts: local
  connection: local
  vars:
    CORE: "Devops with AWS"
    DURATION: "140"
    TRAINER: "sivakumar reddy"
 tasks:
 - name: print vars
#  vars:
#      CORE: "ANSIBLE"
    ansible.builtin.debug:
      msg: "core is: {{ CORE }}, trainer was {{ TRAINER }}"
  vars_prompt:
  - name: promot_bars
    prompt: Please enter name
    private: false

# 1.arg:wq
# 2. tasks:wq

    

