- name: httpd
  hosts: local
  connection: local
  become: true
  tasks:
  - name: httpservice installation
    ansible.builtin.dnf:
      name: httpd
      state: present
    register: httpd_install_result

  - name: httpd_result
    ansible.builtin.debug:
      msg: "installation is completed"
    when: httpd_install_result.rc == 0
