- name: httpd
  hosts: local
  connection: local
  become: true
  vars: 
    Myip: 246.257.345.678
  tasks:
  - name: httpservice installation
    ansible.builtin.dnf:
      name: httpd
      state: present
    register: httpd_install_result

  - name: httpd_result
    ansible.builtin.debug:
      msg: "installation is completed"
    when: httpd_install_result.rc == 0

  - name: httpd_enables
    ansible.builtin.shell: systemctl enable httpd.service 

  - name: httpservice 
    ansible.builtin.service:
      name: httpd
      state: restarted
    register: httpd_restart_result

  - name: httpd_result
    ansible.builtin.debug:
      msg: "start is completed"
    when: httpd_install_result.rc == 0

     
  - name: IP_test_result
    ansible.builtin.debug:
      msg: "{{ Myip | ansible.utils.ip4 }}"



