- name: Add the user 'johnd' with a specific uid and a primary group of 'admin'
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: user creation
    ansible.builtin.user:
      name: puthach
      comment: puthach